export interface INewListing {
  name: string;
  description: string;
  builtMonth: string;
  builtYear: number | string;
  currentlyLivedIn: boolean;
  hasManualAddress: boolean;
  address: string;
  country: string;
  state: string;
  city: string;
  localGovernmentArea: string;
  keyArea?: string;
  nearestLandMark: string;
  streetName: string;
  propertyNumber: string;
  media: {
    id: string;
    name: string;
    type: string;
    url: string;
    purpose: string;
  }[];
  category: string;
  type: string;
  bedrooms: string | number;
  bedroom?: string | number;
  bathrooms: string | number;
  toilets: string | number;
  parkingSpace: string | number;
  rentalPeriod: string;
  fee: number;
  furnishedType: string;
  propertyAge: string;
  lotSize: number | undefined;
  floorLevel: string;
  floorArea: number | undefined;
  servicing: string;
  interiorFeatures: string[];
  exteriorFeatures: string[];
  buildingAmenities: string[];
  facilities: string[];
  kitchenFittings: string[];
  interiorFlooring: string;
  exteriorFlooring: string;
  platformFee: number;
  legalFee: number;
  serviceFee: number;
  cautionFee: number;
  estateFee: number;
  otherFees: {
    name: string;
    fee: number;
  }[];
  representativeId: string;
  tenant: string;
  tenants: any[];
  caretakerId: string;
  propertystatus: string;
  currency: string;
  wifiAccess: string;
  leaseEndDate?: string;
  leaseStartDate?: string;
  dueDayOfPeriod: number;
  isProrated: boolean;
  tenantRentAmount?: number;
  tenantOtherFeesTotal: number;
  lga?: string;
  stateId?: string;
  cityId?: string;
}
