export const icons = {
  edit: (await import("@src/assets/icons/edit.svg")).default,
  bin: (await import("@src/assets/icons/bin.svg")).default,
  eye: (await import("@src/assets/icons/eye.svg")).default,
  eyecolored: (await import("@src/assets/icons/eye-colored.svg")).default,
  info: (await import("@src/assets/icons/info.svg")).default,
  settings: (await import("@src/assets/icons/settings.svg")).default,
  cancel: (await import("@src/assets/icons/cancel.svg")).default,
  arrowleft: (await import("@src/assets/icons/arrow-left.svg")).default,
  arrowright: (await import("@src/assets/icons/arrow-right.svg")).default,
  arrowback: (await import("@src/assets/icons/arrow-back.svg")).default,
  naira: (await import("@src/assets/icons/naira.svg")).default,
  bed: (await import("@src/assets/icons/bed.svg")).default,
  shower: (await import("@src/assets/icons/shower.svg")).default,
  toilet: (await import("@src/assets/icons/toilet.svg")).default,
  headcircle: (await import("@src/assets/icons/head-circle.png")).default,
  profilehead: (await import("@src/assets/icons/profile-head.svg")).default,
  apartment: (await import("@src/assets/icons/apartment.svg")).default,
  camera: (await import("@src/assets/icons/camera.svg")).default,
  user: (await import("@src/assets/icons/user.svg")).default,
  usercircle: (await import("@src/assets/icons/user-circle.svg")).default,
  call: (await import("@src/assets/icons/call.svg")).default,
  mail: (await import("@src/assets/icons/mail.svg")).default,
  location: (await import("@src/assets/icons/location.svg")).default,
};
